<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        <p>
            <input type="text" placeholder="Title" name="title">
        </p>
        <p>
            <textarea placeholder="Text" name="text"></textarea>
        </p>
        <p>
            <input type="submit" value="Send">
        </p>
    </form>
</body>
</html>